Traceback (most recent call last):
  File "/home/thizzy/Desktop/programaci-nSegura/proyecto/manage.py", line 22, in <module>
    main()
  File "/home/thizzy/Desktop/programaci-nSegura/proyecto/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/thizzy/Desktop/aplicacion/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/thizzy/Desktop/aplicacion/lib/python3.12/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/home/thizzy/Desktop/aplicacion/lib/python3.12/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/home/thizzy/Desktop/aplicacion/lib/python3.12/site-packages/django/conf/__init__.py", line 68, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thizzy/Desktop/aplicacion/lib/python3.12/site-packages/django/conf/__init__.py", line 166, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/thizzy/Desktop/programaci-nSegura/proyecto/proyecto/settings.py", line 23, in <module>
    SECRET_KEY = os.environ.get('SECRET_KEY')
                 ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?
